In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

#Logistic Regression

In [ ]:
data = pd.read_csv("veriler.csv")
indep= data.iloc[:,1:4]
dep = data.iloc[:,-1:]


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(indep,dep,test_size=0.33,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.transform(x_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
model_log = LogisticRegression(random_state=0).fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
y_test

cinsiyet
20        k
10        k
14        k
13        k
1         e
21        k
11        k
19        k

In [ ]:
y_pred = model_log.predict(x_test)
y_pred


array(['e', 'k', 'k', 'k', 'e', 'k', 'k', 'k'], dtype=object)

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred,y_test)

array([[1, 1],
       [0, 6]])

#KNN

In [ ]:
data = pd.read_csv("veriler.csv")
indep= data.iloc[:,1:4]
dep = data.iloc[:,-1:]


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(indep,dep,test_size=0.33,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.transform(x_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model_knn = KNeighborsClassifier(n_neighbors=1,metric='minkowski').fit(X_train,y_train)
y_pred = model_knn.predict(X_test)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred,y_test)

array([[1, 1],
       [0, 6]])

#SVM

In [ ]:
data = pd.read_csv("veriler.csv")
indep= data.iloc[:,1:4]
dep = data.iloc[:,-1:]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(indep,dep,test_size=0.33,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.transform(x_test)

In [ ]:
from sklearn.svm import SVC
model_svc= SVC(kernel="rbf").fit(x_train,y_train)
y_pred = model_svc.predict(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred,y_test)

array([[1, 7],
       [0, 0]])

#Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB
model_gnb = GaussianNB().fit(X_train,y_train)
y_pred = model_gnb.predict(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred,y_test)

array([[0, 6],
       [1, 1]])

#Decision Tree Classifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier
model_dtc = DecisionTreeClassifier(criterion="entropy").fit(X_train,y_train)
y_pred = model_dtc.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred,y_test)

array([[1, 1],
       [0, 6]])

#Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model_rf = RandomForestClassifier(criterion="entropy",n_estimators=10).fit(X_train,y_train)
y_pred = model_rf.predict(X_test)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred,y_test)

array([[1, 2],
       [0, 5]])

#Homework

In [3]:
data = pd.read_excel("Iris.xls")
data

sepal length  sepal width  petal length  petal width            iris
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
x= data.iloc[:,0:4]
y= data.iloc[:,-1:]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33,random_state=0)

##Logistic Regression

In [44]:
from sklearn.linear_model import LogisticRegression

In [45]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.transform(x_test)


In [46]:
model_lr = LogisticRegression(random_state=0).fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [47]:
y_pred = model_lr.predict(X_test)

In [48]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred,y_test)

array([[16,  0,  0],
       [ 0, 18,  2],
       [ 0,  1, 13]])

##KNN

In [61]:
from sklearn.neighbors import KNeighborsClassifier
model_knn = KNeighborsClassifier(metric="minkowski",n_neighbors=3).fit(X_train,y_train)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


In [62]:
y_pred = model_knn.predict(X_test)

In [63]:
confusion_matrix(y_test,y_pred)

array([[16,  0,  0],
       [ 0, 18,  1],
       [ 0,  1, 14]])

##SVM

In [64]:
from sklearn.svm import SVC

In [70]:
model_svc = SVC(kernel="linear").fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [71]:
y_pred = model_svc.predict(X_test)

In [72]:
confusion_matrix(y_test,y_pred)

array([[16,  0,  0],
       [ 0, 18,  1],
       [ 0,  0, 15]])

##Naive Bayes

In [73]:
from sklearn.naive_bayes import GaussianNB
model_gnb = GaussianNB().fit(X_train,y_train)
y_pred = model_gnb.predict(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [74]:
confusion_matrix(y_test,y_pred)

array([[16,  0,  0],
       [ 0, 19,  0],
       [ 0,  2, 13]])

##Decision Tree Classifier

In [75]:
from sklearn.tree import DecisionTreeClassifier

In [76]:
model_dtc = DecisionTreeClassifier(criterion="entropy").fit(X_train,y_train)

In [77]:
y_pred = model_dtc.predict(X_test)

In [78]:
confusion_matrix(y_test,y_pred)

array([[16,  0,  0],
       [ 0, 18,  1],
       [ 0,  1, 14]])

##Random Forest

In [79]:
from sklearn.ensemble import RandomForestClassifier

In [92]:
model_rfc = RandomForestClassifier(criterion="entropy",n_estimators=6).fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


In [93]:
y_pred = model_rfc.predict(X_test)

In [94]:
confusion_matrix(y_test,y_pred)

array([[16,  0,  0],
       [ 0, 18,  1],
       [ 0,  0, 15]])