# Working with missing values

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn import preprocessing

In [ ]:

data = pd.read_csv("eksikveriler.csv")
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')#missing_values=eksik değerler, strategy=ne ile değiştereceğimiz.
age = data.iloc[:,1:4].values
imputer = imputer.fit(age[:,1:4]) #1'den 4'e kadar değerleri ortalamasını öğreniyor
age[:,1:4] = imputer.transform(age[:,1:4])#Öğrendiği ortalamaları nan değerler yerine koyuyor
gender = data.iloc[:,-1].values
age

array([[130.  ,  30.  ,  10.  ],
       [125.  ,  36.  ,  11.  ],
       [135.  ,  34.  ,  10.  ],
       [133.  ,  30.  ,   9.  ],
       [129.  ,  38.  ,  12.  ],
       [180.  ,  90.  ,  30.  ],
       [190.  ,  80.  ,  25.  ],
       [175.  ,  90.  ,  35.  ],
       [177.  ,  60.  ,  22.  ],
       [185.  , 105.  ,  33.  ],
       [165.  ,  55.  ,  27.  ],
       [155.  ,  50.  ,  44.  ],
       [160.  ,  58.  ,  28.45],
       [162.  ,  59.  ,  41.  ],
       [167.  ,  62.  ,  55.  ],
       [174.  ,  70.  ,  47.  ],
       [193.  ,  90.  ,  28.45],
       [187.  ,  80.  ,  27.  ],
       [183.  ,  88.  ,  28.  ],
       [159.  ,  40.  ,  29.  ],
       [164.  ,  66.  ,  32.  ],
       [166.  ,  56.  ,  42.  ]])

In [ ]:
#ilk gelen değere 1 sonrasında artarak devam ediyor.
country = data.iloc[:,0:1].values
country[:,0] = le.fit_transform(data.iloc[:,0])
le = preprocessing.LabelEncoder() 
country

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]], dtype=object)

In [ ]:
#veri sayısı kadar column ekleyip binary olarak dolduruyor 1 bulunduğu yer 0 bulunmadığı yer.
ohe = preprocessing.OneHotEncoder()
country = ohe.fit_transform(country).toarray()
country

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [1]:
#verilerin birleştirilmesi
result1 = pd.DataFrame(data=country,index=range(22),columns=['Fr','Tr','Us'])
result2 = pd.DataFrame(data=age,index=range(22),columns=['Height','Weight','Age'])
result3 = pd.DataFrame(data=gender,index=range(22),columns=['Gender'])
result = pd.concat([result1,result2],axis=1)
result1

NameError: ignored

In [ ]:
#Verilerin eğitim ve test olarak parçalanması
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(result,result3,test_size=0.33,random_state=0)
x_train

Fr   Tr   Us  Height  Weight    Age
8   0.0  1.0  0.0   177.0    60.0  22.00
6   0.0  1.0  0.0   190.0    80.0  25.00
16  1.0  0.0  0.0   193.0    90.0  28.45
4   0.0  1.0  0.0   129.0    38.0  12.00
2   0.0  1.0  0.0   135.0    34.0  10.00
5   0.0  1.0  0.0   180.0    90.0  30.00
17  1.0  0.0  0.0   187.0    80.0  27.00
9   0.0  0.0  1.0   185.0   105.0  33.00
7   0.0  1.0  0.0   175.0    90.0  35.00
18  1.0  0.0  0.0   183.0    88.0  28.00
3   0.0  1.0  0.0   133.0    30.0   9.00
0   0.0  1.0  0.0   130.0    30.0  10.00
15  1.0  0.0  0.0   174.0    70.0  47.00
12  0.0  0.0  1.0   160.0    58.0  28.45

In [ ]:
#Verilerin scale edilmesi
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.fit_transform(x_test)
X_test

array([[ 1.29099445, -0.37796447, -1.        ,  0.47240026,  1.32853794,
        -0.24991255],
       [-0.77459667, -0.37796447,  1.        ,  0.54952683,  0.20439045,
        -0.64977262],
       [-0.77459667, -0.37796447,  1.        ,  0.70377998,  0.91975703,
         1.58944379],
       [-0.77459667, -0.37796447,  1.        ,  0.31814711,  0.61317136,
         0.46983559],
       [-0.77459667,  2.64575131, -1.        , -2.53553608, -1.73731884,
        -1.92932485],
       [ 1.29099445, -0.37796447, -1.        ,  0.6266534 ,  0.30658568,
         0.5498076 ],
       [-0.77459667, -0.37796447,  1.        , -0.2217389 , -0.30658568,
         0.70975163],
       [ 1.29099445, -0.37796447, -1.        ,  0.08676739, -1.32853794,
        -0.48982859]])

8     k
6     e
16    e
4     e
2     k
5     e
17    e
9     e
7     e
18    e
3     k
0     e
15    e
12    k
Name: Gender, dtype: object