In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv("Churn_Modelling.csv")
data.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [9]:
x= data.iloc[:,3:13].values
y=data.iloc[:,-1:].values

In [11]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

In [14]:
x[:,1]=le.fit_transform(x[:,1])

In [15]:
le2 = preprocessing.LabelEncoder()

In [16]:
x[:,2]=le.fit_transform(x[:,2])

In [19]:
x[:,1]

array([0, 2, 0, ..., 0, 1, 0], dtype=object)

In [20]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer 

In [23]:
#birden fazla column'un aynı anda dönüştürülmesi için kullanılıyor.
ohe = ColumnTransformer([('ohe',OneHotEncoder(dtype='float'),[1])],remainder='passthrough')
x= ohe.fit_transform(x)
x=x[:,1:]

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33,random_state=0)

In [26]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.fit_transform(x_test)

In [42]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [43]:
classifier = Sequential()
classifier.add(Dense(6,activation='relu',input_dim=11))

In [44]:
classifier.add(Dense(6,activation='relu'))

In [45]:
classifier.add(Dense(1,activation='sigmoid'))

In [46]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [47]:
classifier.fit(X_train,y_train,epochs=50)

Epoch 1/50
210/210 [==============================] - 6s 1ms/step - loss: 0.5596 - accuracy: 0.7566
Epoch 2/50
210/210 [==============================] - 0s 1ms/step - loss: 0.4678 - accuracy: 0.7936
Epoch 3/50
210/210 [==============================] - 0s 1ms/step - loss: 0.4601 - accuracy: 0.7900
Epoch 4/50
210/210 [==============================] - 0s 1ms/step - loss: 0.4417 - accuracy: 0.7996
Epoch 5/50
210/210 [==============================] - 0s 1ms/step - loss: 0.4479 - accuracy: 0.7924
Epoch 6/50
210/210 [==============================] - 0s 1ms/step - loss: 0.4332 - accuracy: 0.8012
Epoch 7/50
210/210 [==============================] - 0s 1ms/step - loss: 0.4258 - accuracy: 0.8030
Epoch 8/50
210/210 [==============================] - 0s 1ms/step - loss: 0.4256 - accuracy: 0.8032
Epoch 9/50
210/210 [==============================] - 0s 1ms/step - loss: 0.4296 - accuracy: 0.8035
Epoch 10/50
210/210 [==============================] - 0s 1ms/step - loss: 0.4276 - accuracy: 0.8044

In [48]:
y_pred = classifier.predict(X_test)

In [51]:
y_pred = (y_pred > 0.5)

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [52]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[2500,  117],
       [ 372,  311]])